name: Generate Contribution Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution animation
        uses: Platane/snk@v3
        with:
          github_user_name: vaibhcodes
          outputs: |
            dist/github-snake.svg?palette=github-light&color_snake=%237c3aed
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23a78bfa

      - name: Publish animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
