<p align="center">
  <picture>
    <source
      media="(prefers-color-scheme: dark)"
      srcset="https://raw.githubusercontent.com/vaibhcodes/vaibhcodes/output/github-snake-dark.svg"
    />
    <source
      media="(prefers-color-scheme: light)"
      srcset="https://raw.githubusercontent.com/vaibhcodes/vaibhcodes/output/github-snake.svg"
    />
    <img
      src="https://raw.githubusercontent.com/vaibhcodes/vaibhcodes/output/github-snake.svg"
      alt="Vaibhav's contribution journey"
    />
  </picture>
</p>
