name: Generate Contribution Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: vaibhcodes
          outputs: |
            dist/github-snake.svg?color_snake=%237c3aed
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23a78bfa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
          commit_message: Update contribution animation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
