name: Generate Contribution Animation

on:
  schedule:
    - cron: "0 */24 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Generate contribution animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          outputs: |
            dist/contribution-animation.svg?color_snake=#00E5FF&color_dots=#0B1220,#102A43,#145DA0,#00A8E8,#00E5FF
            dist/contribution-animation-dark.svg?color_snake=#00E5FF&color_dots=#05070D,#0B1F33,#123F5A,#0088CC,#00E5FF

      - name: Publish animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
